config/routes.rb
Rails.application.routes.draw do
  get 'tags/:tag', to: 'tracker_tasks#index', as: :tag
  resources :tracker_users

  resources :tracker_tasks
  
  get 'tracker_tasks/:id/act/:execute', to: 'tracker_tasks#act', as: :act

  resources :tracker_projects

  resources :projects

  get 'welcome/index'

  devise_for :users

   root 'welcome#index'

end

app/models/tracker_project.rb
class TrackerProject < ActiveRecord::Base
  has_many :tracker_tasks
  
      def to_label

    "#{name}"
  end
end

app/controllers/tracker_projects_controller.rb
class TrackerProjectsController < ApplicationController
  before_action :set_tracker_project, only: [:show, :edit, :update, :destroy]
  before_action :check_adminity, only: [:edit, :update, :destroy, :new, :delete, :create]

  # GET /tracker_projects
  # GET /tracker_projects.json
  def index
    @tracker_projects = TrackerProject.all
  end

  # GET /tracker_projects/1
  # GET /tracker_projects/1.json
  def show
  end

  # GET /tracker_projects/new
  def new
    @tracker_project = TrackerProject.new
  end

  # GET /tracker_projects/1/edit
  def edit
  end

  # POST /tracker_projects
  # POST /tracker_projects.json
  def create
    @tracker_project = TrackerProject.new(tracker_project_params)

    respond_to do |format|
      if @tracker_project.save
        format.html { redirect_to @tracker_project, notice: 'Tracker project was successfully created.' }
        format.json { render :show, status: :created, location: @tracker_project }
      else
        format.html { render :new }
        format.json { render json: @tracker_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracker_projects/1
  # PATCH/PUT /tracker_projects/1.json
  def update
    respond_to do |format|
      if @tracker_project.update(tracker_project_params)
        format.html { redirect_to @tracker_project, notice: 'Tracker project was successfully updated.' }
        format.json { render :show, status: :ok, location: @tracker_project }
      else
        format.html { render :edit }
        format.json { render json: @tracker_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracker_projects/1
  # DELETE /tracker_projects/1.json
  def destroy
    @tracker_project.destroy
    respond_to do |format|
      format.html { redirect_to tracker_projects_url, notice: 'Tracker project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tracker_project
      @tracker_project = TrackerProject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tracker_project_params
      params.require(:tracker_project).permit(:name, :description)
    end
end

app/helpers/tracker_projects_helper.rb
module TrackerProjectsHelper
end

app/views/tracker_projects/_form.html.haml
= simple_form_for(@tracker_project) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description

  .form-actions
    = f.button :submit

app/views/tracker_projects/edit.html.haml
%h1 Editing tracker_project

= render 'form'

= link_to 'Show', @tracker_project
\|
= link_to 'Back', tracker_projects_path

app/views/tracker_projects/index.html.haml
%h1 Listing tracker_projects

%table
  %tr
    %th Name
    %th Description
    %th
    %th
    %th

  - @tracker_projects.each do |tracker_project|
    %tr
      %td= tracker_project.name
      %td= tracker_project.description
      %td= link_to 'Show', tracker_project
      %td= link_to 'Edit', edit_tracker_project_path(tracker_project)
      %td= link_to 'Destroy', tracker_project, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Tracker project', new_tracker_project_path

app/views/tracker_projects/new.html.haml
%h1 New tracker_project

= render 'form'

= link_to 'Back', tracker_projects_path

app/views/tracker_projects/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @tracker_project.name
%p
  %b Description:
  = @tracker_project.description

= link_to 'Edit', edit_tracker_project_path(@tracker_project)
\|
= link_to 'Back', tracker_projects_path