config/routes.rb
Rails.application.routes.draw do
  get 'tags/:tag', to: 'tracker_tasks#index', as: :tag
  resources :tracker_users

  resources :tracker_tasks
  
  get 'tracker_tasks/:id/act/:execute', to: 'tracker_tasks#act', as: :act

  resources :tracker_projects

  resources :projects

  get 'welcome/index'

  devise_for :users

   root 'welcome#index'

end

app/models/tracker_task.rb
class TrackerTask < ActiveRecord::Base
  acts_as_taggable
  belongs_to :initiator, class_name: 'TrackerUser'
  belongs_to :user, class_name: 'TrackerUser'
  belongs_to :tracker_project, class_name: 'TrackerProject'

  validates_presence_of :user
  validates_presence_of :initiator
  validates_presence_of :title
  validates_presence_of :description
  validates_presence_of :cost
  validates_presence_of :tracker_project

  state_machine :state, :initial => :initialized do
    event :accept do
      transition :initialized => :accepted
    end
    event :verify do
      transition :accepted => :verified
    end
    event :start_process do
      transition :verified => :in_process
    end
    event :finish_process do
      transition :in_process => :in_test
    end
    event :test_passed do
      transition :in_test => :executed
    end    
    
        
    
  end

end

app/controllers/tracker_tasks_controller.rb
class TrackerTasksController < ApplicationController
  before_action :set_tracker_task, only: [:show, :edit, :update, :destroy, :act]
  before_action :check_adminity, only: [:new, :edit, :update, :destroy, :create, :delete]


  def act
    if params[:execute]
      TrackerTask.find(@tracker_task.id).fire_state_event(params[:execute]);

    else
  
    end
    @z = params
    params.inspect
  #  redirect_to tracker_task_path(@tracker_task.id)
    redirect_to tracker_tasks_path()
  end
  # GET /tracker_tasks
  # GET /tracker_tasks.json
  def index


    
    
    @states = ['initialized', 'accepted', 'verified', 'in_process', 'in_test', 'executed']
    @acts   = ['accept', 'verify', 'start_process', 'finish_process', 'test_passed', 'none']
    if params[:tag]
    @tracker_tasks = TrackerTask.tagged_with(params[:tag]).all  
    else 
    @tracker_tasks = TrackerTask.all
    end
  end

  # GET /tracker_tasks/1
  # GET /tracker_tasks/1.json
  def show
  end

  # GET /tracker_tasks/new
  def new
    @tracker_task = TrackerTask.new
    @tracker_task.initiator_id = current_user.id
  end

  # GET /tracker_tasks/1/edit
  def edit
  end

  # POST /tracker_tasks
  # POST /tracker_tasks.json
  def create
    @tracker_task = TrackerTask.new(tracker_task_params)

    respond_to do |format|
      if @tracker_task.save
        format.html { redirect_to @tracker_task, notice: 'Tracker task was successfully created.' }
        format.json { render :show, status: :created, location: @tracker_task }
      else
        format.html { render :new }
        format.json { render json: @tracker_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracker_tasks/1
  # PATCH/PUT /tracker_tasks/1.json
  def update
    respond_to do |format|
      if @tracker_task.update(tracker_task_params)
        format.html { redirect_to @tracker_task, notice: 'Tracker task was successfully updated.' }
        format.json { render :show, status: :ok, location: @tracker_task }
      else
        format.html { render :edit }
        format.json { render json: @tracker_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracker_tasks/1
  # DELETE /tracker_tasks/1.json
  def destroy
    @tracker_task.destroy
    respond_to do |format|
      format.html { redirect_to tracker_tasks_url, notice: 'Tracker task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tracker_task
      @tracker_task = TrackerTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tracker_task_params
      params.require(:tracker_task).permit(:cost,
       :title, :description, :initiator_id, 
       :user_id, :tracker_project_id, :tag_list)
    end
end

app/helpers/tracker_tasks_helper.rb
module TrackerTasksHelper
end

app/views/tracker_tasks/Copy of index.html.haml
%h1 Listing tracker_tasks
%div= link_to 'AllTasks', tracker_tasks_path
= @z

  

%table
  %tr
    %th Initialized
    %th Accepted
    %th Verified
    %th In Process
    %th In Test
    %th Executed
  
  - @tracker_tasks.each do |tracker_task|
  - @states.each do |state|
    %tr
      %td{:class=>'taskcell'}
        - if tracker_task.state == 'initialized' 
          - # Stuff like ______ activates the if statement
          = render tracker_task 
          = link_to 'Accept', act_path(tracker_task, :execute=>:accept)
        - else
          - # Stuff like _____ activates the else statement
          &amp;
      %td{:class=>'taskcell'}
        - if tracker_task.state == 'accepted'
          - # Stuff like ______ activates the if statement
          = render tracker_task 
          = link_to 'Verify', act_path(tracker_task, :execute=>:verify)          
        - else
          - # Stuff like _____ activates the else statement
          &amp;
      %td{:class=>'taskcell'}
        - if tracker_task.state == 'verified'
          - # Stuff like ______ activates the if statement
          = render tracker_task 
          = link_to 'Start Processing', act_path(tracker_task, :execute=>:start_process)          
        - else
          - # Stuff like _____ activates the else statement
          &amp;
      %td{:class=>'taskcell'}
        - if tracker_task.state == 'in_process' 
          - # Stuff like ______ activates the if statement
          = render tracker_task 
          = link_to 'Finish Process', act_path(tracker_task, :execute=>:finish_process)
          - # Stuff like _____ activates the else statement
          &amp;
      %td{:class=>'taskcell'}
        - if tracker_task.state == 'in_test'
          - # Stuff like ______ activates the if statement
          = render tracker_task 
          = link_to 'Test_Passed', act_path(tracker_task, :execute=>:test_passed   )      
        - else
          - # Stuff like _____ activates the else statement
          &amp;            
      %td{:class=>'taskcell'}
        - if tracker_task.state == 'executed'
          - # Stuff like ______ activates the if statement
          = render tracker_task 
        - else
          - # Stuff like _____ activates the else statement
          &amp;                         

                             

%br

= link_to 'New Tracker task', new_tracker_task_path

app/views/tracker_tasks/_form.html.haml
= simple_form_for(@tracker_task) do |f|
  = f.error_notification

  .form-inputs
    = f.input :cost
    = f.input :title
    = f.input :description
    = f.association :tracker_project, :item_wrapper_class => 'TrackerProject'
    = f.association :initiator, :item_wrapper_class => 'TrackerUser'
    = f.association :user, :item_wrapper_class => 'TrackerUser'
    = f.input :tag_list, :label => 'tags, delimited by comma'

  .form-actions
    = f.button :submit

app/views/tracker_tasks/_tracker_task.html.haml
%table{:class=>'taskcelltable'}
  %tr
    %td 'Title'
    %td= tracker_task.title
  %tr
    %td 'User'
    %td= tracker_task.user.email
  %tr
    %td Destription
    %td= tracker_task.description
  %tr
    %td Project
    %td= tracker_task.tracker_project.name
  %tr 
    %td tags
    %td= raw tracker_task.tag_list.map { |tag| link_to tag, tag_path(tag)}.join(', ')
  %tr    
    %td= link_to 'Edit', edit_tracker_task_path(tracker_task)
    %td= link_to 'Destroy', tracker_task, :method => :delete, :data => { :confirm => 'Are you sure?' }    

app/views/tracker_tasks/edit.html.haml
%h1 Editing tracker_task

= render 'form'

= link_to 'Show', @tracker_task
\|
= link_to 'Back', tracker_tasks_path

app/views/tracker_tasks/index.html.haml
%h1 Listing tracker_tasks
%div= link_to 'AllTasks', tracker_tasks_path
= @z

  

%table
  %tr
    %th Initialized
    %th Accepted
    %th Verified
    %th In Process
    %th In Test
    %th Executed
  
  - @tracker_tasks.each do |tracker_task|
    %tr
      - @states.each_with_index do |state, index|

        %td{:class=>'taskcell'}
          - if tracker_task.state == state
            - # Stuff like ______ activates the if statement
            = render tracker_task 
            - if @acts[index] != 'none'
              = link_to @acts[index], act_path(tracker_task, :execute=>@acts[index])
            - else
              %div terminal state
          - else
            - # Stuff like _____ activates the else statement
            &amp;


                             

%br

= link_to 'New Tracker task', new_tracker_task_path

app/views/tracker_tasks/new.html.haml
%h1 New tracker_task

= render 'form'

= link_to 'Back', tracker_tasks_path

app/views/tracker_tasks/show.html.haml
%p#notice= notice

%p
  %b Cost:
  = @tracker_task.cost
%p
  %b Title:
  = @tracker_task.title
%p
  %b Project:
  = @tracker_task.tracker_project.name
%p  
  %b Description:
  = @tracker_task.description
%p
  %b Initiator:
  = @tracker_task.initiator.email
%p
  %b User:
  = @tracker_task.user.email
  = @z

= link_to 'Edit', edit_tracker_task_path(@tracker_task)
\|
= link_to 'Back', tracker_tasks_path

app/views/tracker_tasks/simpleindex.html.haml
%h1 Listing tracker_tasks
%div= link_to 'AllTasks', tracker_tasks_path

%table
  %tr
    %th Initialized
    %th Title
    %th Description
    %th Initiator
    %th User
    %th Project
    %th Tags
    %th
    %th
    %th

  - @tracker_tasks.each do |tracker_task|
    %tr
      %td= tracker_task.cost
      %td= tracker_task.title
      %td= tracker_task.description
      %td= tracker_task.initiator_id
      %td= tracker_task.user.email
      %td= tracker_task.tracker_project.name
      %td= raw tracker_task.tag_list.map { |tag| link_to tag, tag_path(tag)}.join(', ')
      %td= link_to 'Show', tracker_task
      %td= link_to 'Edit', edit_tracker_task_path(tracker_task)
      %td= link_to 'Destroy', tracker_task, :method => :delete, :data => { :confirm => 'Are you sure?' }
      %div= render tracker_task

%br

= link_to 'New Tracker task', new_tracker_task_path