config/routes.rb
Rails.application.routes.draw do
  get 'tags/:tag', to: 'tracker_tasks#index', as: :tag
  resources :tracker_users

  resources :tracker_tasks
  
  get 'tracker_tasks/:id/act/:execute', to: 'tracker_tasks#act', as: :act

  resources :tracker_projects

  resources :projects

  get 'welcome/index'

  devise_for :users

   root 'welcome#index'

end

app/models/tracker_user.rb
class TrackerUser < User
  
  has_many :initiated_tracker_tasks, class_name: 'TrackerTask', :foreign_key => 'initiator_id'
  has_many :gotten_tracker_tasks, class_name: 'TrackerTask', :foreign_key => 'user_id'
  
    def to_label
    #castle.castle_name
    "#{email}"
  end
  
  
  
end

app/controllers/tracker_users_controller.rb
class TrackerUsersController < ApplicationController
  before_action :set_tracker_user, only: [:show, :edit, :update, :destroy]
  before_action :check_adminity

  # GET /tracker_users
  # GET /tracker_users.json
  def index
    @tracker_users = TrackerUser.all
  end

  # GET /tracker_users/1
  # GET /tracker_users/1.json
  def show
  end

  # GET /tracker_users/new
  def new
    @tracker_user = TrackerUser.new
  end

  # GET /tracker_users/1/edit
  def edit
  end

  # POST /tracker_users
  # POST /tracker_users.json
  def create
    @tracker_user = TrackerUser.new(tracker_user_params)
    @tracker_user.password = @tracker_user.email

    respond_to do |format|
      if @tracker_user.save
        format.html { redirect_to @tracker_user, notice: 'Tracker user was successfully created.' }
        format.json { render :show, status: :created, location: @tracker_user }
      else
        format.html { render :new }
        format.json { render json: @tracker_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracker_users/1
  # PATCH/PUT /tracker_users/1.json
  def update
    respond_to do |format|
      if @tracker_user.update(tracker_user_params)
        format.html { redirect_to @tracker_user, notice: 'Tracker user was successfully updated.' }
        format.json { render :show, status: :ok, location: @tracker_user }
      else
        format.html { render :edit }
        format.json { render json: @tracker_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracker_users/1
  # DELETE /tracker_users/1.json
  def destroy
    @tracker_user.destroy
    respond_to do |format|
      format.html { redirect_to tracker_users_url, notice: 'Tracker user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tracker_user
      @tracker_user = TrackerUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tracker_user_params
      params.require(:tracker_user).permit(:email, :is_admin)
    end
end

app/helpers/tracker_users_helper.rb
module TrackerUsersHelper
end

app/views/tracker_users/_form.html.haml
= simple_form_for(@tracker_user) do |f|
  = f.error_notification

  .form-inputs
    = f.input :email
    = f.input :is_admin

  .form-actions
    = f.button :submit

app/views/tracker_users/edit.html.haml
%h1 Editing tracker_user

= render 'form'

= link_to 'Show', @tracker_user
\|
= link_to 'Back', tracker_users_path

app/views/tracker_users/index.html.haml
%h1 Listing tracker_users

%table
  %tr
    %th Email
    %th Is admin
    %th
    %th
    %th

  - @tracker_users.each do |tracker_user|
    %tr
      %td= tracker_user.email
      %td= tracker_user.is_admin
      %td= link_to 'Show', tracker_user
      %td= link_to 'Edit', edit_tracker_user_path(tracker_user)
      %td= link_to 'Destroy', tracker_user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Tracker user', new_tracker_user_path

app/views/tracker_users/new.html.haml
%h1 New tracker_user

= render 'form'

= link_to 'Back', tracker_users_path

app/views/tracker_users/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @tracker_user.email
%p
  %b Is admin:
  = @tracker_user.is_admin

= link_to 'Edit', edit_tracker_user_path(@tracker_user)
\|
= link_to 'Back', tracker_users_path